'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace GuillermoNavarro_T5

    Partial Public Class formulario
        Public Property id As Integer
        Public Property nombreUsuario As String
        Public Property clave As String
        Public Property correo As String
        Public Property apellido As String
        Public Property pais As String
        Public Property provincia As String
        Public Property codigoPostal As String
        Public Property sexo As String
        Public Property fechaNacimiento As String
        Public Property comentario As String
    
    End Class

End Namespace
